server:
  port: 8081

spring:
  application:
    name: member-service
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/member_db?authSource=admin

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 1 day
