services:
  postgres-cart:
    image: postgres:16-alpine
    container_name: postgres-cart
    environment:
      POSTGRES_DB: cartdb
      POSTGRES_USER: cart_user
      POSTGRES_PASSWORD: cart_pass
    ports:
      - "5434:5432"
    volumes:
      - postgres-cart-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cart_user -d cartdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-cart-data:
